run:
  timeout: 5m
  tests: false

issues:
  exclude-rules:
    - path: 'hp/'
      linters:
        - nosnakecase
        - stylecheck
    - path: 'main.go'
      linters:
        - nosnakecase
    - path: 'hp/ilo/firmware.go'
      linters:
        - wastedassign

linters:
   enable-all: true
   disable:
     - golint # TODO fix
     - revive
     - cyclop
     - depguard
     - dupl
     - exhaustivestruct
     - exhaustruct
     - forbidigo
     - forcetypeassert
     - gci
     - gochecknoglobals
     - gochecknoinits
     - godot
     - godox
     - goerr113
     - gofumpt
     - gomnd
     - lll
     - musttag
     - nakedret
     - nlreturn
     - nolintlint
     - nonamedreturns
     - tagliatelle
     - varnamelen
     - wrapcheck
linters-settings:
   estif:
     min-complexity: 4
   maligned:
     suggest-new: true
