run:
  timeout: 5m
  tests: false

issues:
  exclude-rules:
    - path: 'hp/'
      linters:
        - nosnakecase
        - stylecheck
    - path: 'main.go'
      linters:
        - nosnakecase
        - funlen
        - gocognit
    - path: 'hp/ilo/firmware.go'
      linters:
        - wastedassign
        - exhaustive
    - path: 'snmp/snmpwalk.go'
      linters:
        - funlen
        - perfsprint
    - path: 'snmp/util.go'
      linters:
        - perfsprint
    - path: 'hp/mib/cpq_sm_cntrl.go'
      linters:
        - golint

linters:
   enable-all: true
   disable:
     - revive
     - cyclop
     - depguard
     - dupl
     - exhaustivestruct
     - exhaustruct
     - forbidigo
     - forcetypeassert
     - gci
     - gochecknoglobals
     - gochecknoinits
     - godot
     - godox
     - gofumpt
     - err113
     - mnd
     - lll
     - musttag
     - nakedret
     - nlreturn
     - nolintlint
     - nonamedreturns
     - tagliatelle
     - varnamelen
     - wrapcheck
